---
.travis.yml:
  docker_sets:
    - set: docker/ubuntu-16.04
    - set: docker/ubuntu-14.04
    - set: docker/centos-7
    - set: docker/debian-8
  secure: "GOhttACuJt+3s38m4WnW5RuTgwqaAoeEQnNT+X1Ukn7KdcIk4KV8NzYU/CC0VIm8lUOnBWYJKEC4ixX/J/4Wbxox2RAoKMQrO++L0DB1zTCJnq9SfoUBMaQhXvLu+PbxAR0p3P47ozra0C+pOWDpOaxT9ecufrPQt9W9Z4aY/bs="
